version: "3.8"
name: api-architecture
services:
  mail:
    restart: on-failure
    image: dockage/mailcatcher:0.9.0
    ports:
      - "1080:1080"
      - "1025:1025"
  api:
    build:
      context: .
      dockerfile: backend.Dockerfile
    command: npm run start:dev
    volumes:
      - .:/usr/app
      - /usr/app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    depends_on: ["mail"]
